project_id = "nerhxpfcccyggmmxdugc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.machine-connector]
verify_jwt = false

[functions.ads-connector]
verify_jwt = false